[package]
name = "browser_workspace_gen"
version = "0.1.0"
edition = "2021"

[dependencies]
askama = "0.12.1"
clap = { version = "4.5.17", features = ["derive"] }
serde = { version = "1.0.217", features = ["serde_derive"] }
serde_json = "1.0.137"
