name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Prepare release notes
        run: .github/workflows/release_prep.sh > release_notes.txt

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          prerelease: false
          body_path: release_notes.txt
          # Use GH feature to populate the changelog automatically
          generate_release_notes: true
          files: |
            rules_playwright-*.tar.gz
          fail_on_unmatched_files: true
